### ISSUE TITLE
Stable diffusion img2img CUDA out of memory error

### ISSUE THREAD

**Issue by usamaehsan** [replicate/replicate-python#55]
replicate.exceptions.ModelError: CUDA out of memory. Tried to allocate 26.11 GiB (GPU 0; 39.59 GiB total capacity; 31.80 GiB already allocated; 5.90 GiB free; 31.97 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by uranity** [comment]
Still not working.. A have in other model:
`ModelError: CUDA out of memory. Tried to allocate 2.75 GiB (GPU 0; 39.59 GiB total capacity; 27.03 GiB already allocated; 2.07 GiB free; 35.64 GiB reserved in total by PyTorch)`

Anyone who replicate is working properly?

**Comment by jamesopti** [comment]
@uranity Did you ever solve this?

I'm trying to follow [these instructions](https://replicate.com/jingyunliang/swinir/api) and have hit the same error.

**Comment by usamaehsan** [comment]
@jamesopti only large images gives this error.
To solve this error, decrease image size before using them.

**Comment by barshag** [comment]
Here too...  Can't Replicate fix it?
(Is it server or local configuration?)

**Comment by onehumanbeing** [comment]
I got this issues and tried raw http request, found the traceback was from replicate's server. I solved this problem just by adding my credit card and the request will be run on an available server. Money deals with this issues.

**Comment by barshag** [comment]
Thanks for the reply!
I already added my credit card, but still got this error :(
Can you share the code? (I tried to use Controlnet-Canny )

**Comment by mattt** [comment]
This repo tracks the development of Replicate's Python library. This issue appears to concern a Stable Diffusion model hosted on Replicate, so there's not much to be done here. If this is still an issue, please consider opening an issue in the GitHub repo for that model (click on the <kbd>GitHub</kbd> button on the model page), or ask a question on [Discord](https://discord.gg/replicate)
